server:
  port: 8081

#Application name
spring:
  application:
    name: spring-cloud-provider

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
