server:
  port: 8082

#Application name
spring:
  application:
    name: spring-cloud-consumer

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

# application parameters
app:
  service-url: http://spring-cloud-provider/
